development:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_development
  pool: 5
  username: order_supplies
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_test
  pool: 5
  username: order_supplies
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_production
  pool: 5
  username: order_supplies
  password:
