development:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_development
  pool: 5
  username: upnxt
  password: upnxt

test:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_test
  pool: 5
  username: upnxt
  password: upnxt

production:
  adapter: postgresql
  encoding: unicode
  database: OrderSupplies_production
  pool: 5
  username: upnxt
  password: upnxt
